apiVersion: v2
name: spar
description: A Helm chart for Social Payments Account Registry
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: spar-mapper-api
  version: 0.1.0
  condition: spar-mapper-api.enabled
- name: spar-self-service-api
  version: 0.1.0
  condition: spar-self-service-api.enabled
- name: spar-self-service-ui
  version: 0.1.0
  condition: spar-self-service-ui.enabled
- name: sunbird-rc-g2p-mapper-registry
  version: 0.1.0
  repository: https://openg2p.github.io/openg2p-helm
  condition: sunbird-rc-g2p-mapper-registry.enabled
