{{- if .Values.postgresInit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "selfservice.fullname" . }}-postgres-init
  labels:
    {{- include "selfservice.labels" . | nindent 4 }}
  {{- if .Values.postgresInit.hookAnnotations }}
  annotations: {{- include "selfservice.tpl" (dict "value" .Values.postgresInit.hookAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.postgresInit.backoffLimit }}
  template:
    spec:
      restartPolicy: {{ .Values.postgresInit.restartPolicy }}
      serviceAccountName: {{ include "selfservice.serviceAccountName" . }}
      containers:
        - name: postgres-init
          image: {{ .Values.postgresInit.image }}
          imagePullPolicy: {{ .Values.postgresInit.imagePullPolicy }}
          env: {{- include "selfservice.envVars" . | nindent 12 }}
            {{- include "selfservice.postgresInitEnvVars" . | nindent 12 }}
          command: {{- toYaml .Values.postgresInit.command | nindent 12 }}
{{- end }}
