global:
  benePortalHostname: bene-portal-api.sandbox.openg2p.net

  pbmsDbUsername: "postgres"
  pbmsDbHostname: "localhost"
  pbmsDbPort: "5432"
  pbmsDbName: "pbmsdb"
  pbmsDbSecretName: "pbms-db-secret"

  bgTaskDbUsername: "postgres"
  bgTaskDbHostname: "localhost"
  bgTaskDbPort: "5432"
  bgTaskDbName: "bgtaskdb"
  bgTaskDbSecretName: "bgtask-db-secret"

replicaCount: 1
image:
  repository: openg2p/openg2p-pbms-bene-portal-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

envVars:
  # PBMS Database (PBMS)
  PBMS_BENE_PORTAL_API_DB_USERNAME_PBMS: "{{ .Values.global.pbmsDbUsername | default "postgres" }}"
  PBMS_BENE_PORTAL_API_DB_HOSTNAME_PBMS: "{{ .Values.global.pbmsDbHostname | default "localhost" }}"
  PBMS_BENE_PORTAL_API_DB_PORT_PBMS: "{{ .Values.global.pbmsDbPort | default "5432" }}"
  PBMS_BENE_PORTAL_API_DB_DBNAME_PBMS: "{{ .Values.global.pbmsDbName | default "pbmsdb" }}"

  # Background Task Database (BG_TASK)
  PBMS_BENE_PORTAL_API_DB_USERNAME_BG_TASK: "{{ .Values.global.bgTaskDbUsername | default "postgres" }}"
  PBMS_BENE_PORTAL_API_DB_HOSTNAME_BG_TASK: "{{ .Values.global.bgTaskDbHostname | default "localhost" }}"
  PBMS_BENE_PORTAL_API_DB_PORT_BG_TASK: "{{ .Values.global.bgTaskDbPort | default "5432" }}"
  PBMS_BENE_PORTAL_API_DB_DBNAME_BG_TASK: "{{ .Values.global.bgTaskDbName | default "bgtaskdb" }}"

envVarsFrom:
  # PBMS Database (PBMS) password
  PBMS_BENE_PORTAL_API_DB_PASSWORD_PBMS:
    secretKeyRef:
      name: "{{ .Values.global.pbmsDbSecretName | default "pbms-db-secret" }}"
      key: password
  # Background Task Database (BG_TASK) password
  PBMS_BENE_PORTAL_API_DB_PASSWORD_BG_TASK:
    secretKeyRef:
      name: "{{ .Values.global.bgTaskDbSecretName | default "bgtask-db-secret" }}"
      key: password

containerPort: 8000

service:
  type: ClusterIP
  port: 80

resources: {}
  #  requests:
  #    cpu: 500m
  #    memory: 2G

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

readinessProbe:
  httpGet:
    path: /ping
    port: 8000
  failureThreshold: 20
  periodSeconds: 30
  timeoutSeconds: 10
  initialDelaySeconds: 30

livenessProbe:
  httpGet:
    path: /ping
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 60
  failureThreshold: 5

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  helm.sh/revision: '{{ .Release.Revision }}'

podSecurityContext: {}
  # fsGroup: 2000

containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

updateStrategy:
  type: RollingUpdate

command: []
args: []

postgresCheckerInit:
  enabled: true
  image: jbergknoff/postgresql-client
  command:
  - 'sh'
  - '-c'
  - |
      until pg_isready -U "${PBMS_BENE_PORTAL_API_DB_USERNAME_PBMS}" -h "${PBMS_BENE_PORTAL_API_DB_HOSTNAME_PBMS}" -p "${PBMS_BENE_PORTAL_API_DB_PORT_PBMS:-5432}" -d "${PBMS_BENE_PORTAL_API_DB_DBNAME_PBMS}"; do
        echo "PBMS database not ready, waiting..."
        sleep 3
      done
      until pg_isready -U "${PBMS_BENE_PORTAL_API_DB_USERNAME_BG_TASK}" -h "${PBMS_BENE_PORTAL_API_DB_HOSTNAME_BG_TASK}" -p "${PBMS_BENE_PORTAL_API_DB_PORT_BG_TASK:-5432}" -d "${PBMS_BENE_PORTAL_API_DB_DBNAME_BG_TASK}"; do
        echo "BG_TASK database not ready, waiting..."
        sleep 3
      done

ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - path: /api/bene-portal(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ include "beneportal.fullname" . }}'
    destinationPort: '{{ .Values.service.port }}'
    prefix: /api/bene-portal/
    rewriteUri: "/"
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""
