apiVersion: v2
name: spar
description: A Helm chart for OpenG2P SPAR
type: application
version: 1.1.0-develop
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: spar-mapper-api
  version: 1.1.0-develop
  condition: spar-mapper-api.enabled
- name: spar-self-service-api
  version: 1.1.0-develop
  condition: spar-self-service-api.enabled
- name: spar-self-service-ui
  version: 1.1.0-develop
  condition: spar-self-service-ui.enabled
- name: artifactory
  version: 12.0.2
  repository: https://openg2p.github.io/openg2p-helm
  condition: artifactory.enabled
- name: keymanager
  version: 12.0.2
  repository: https://openg2p.github.io/openg2p-helm
  condition: keymanager.enabled
- name: softhsm
  repository: https://mosip.github.io/mosip-helm
  version: 12.0.1
  condition: softhsm.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P SPAR"
