apiVersion: v2
name: spar
description: A Helm chart for OpenG2P SPAR
type: application
version: 1.0.0
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: spar-mapper-api
  version: 1.0.0
  condition: spar-mapper-api.enabled
- name: spar-self-service-api
  version: 1.0.0 
  condition: spar-self-service-api.enabled
- name: spar-self-service-ui
  version: 1.0.0 
  condition: spar-self-service-ui.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
xyds: hello
annotations:
  catalog.cattle.io/display-name: "OpenG2P SPAR"
