apiVersion: v2
name: spar
description: A Helm chart for OpenG2P SPAR
type: application
version: 2.0.0-develop 
dependencies:
- name: postgresql
  repository: https://openg2p.github.io/openg2p-helm
  version: 15.5.38
  condition: postgresql.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P SPAR"
