{{- if .Values.postgresql.enabled }}
{{- if .Values.postgresql.istio.enabled }}
{{- if .Values.postgresql.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  labels:
    {{- include "spar.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.postgresql.istio.gateway.ingressController | nindent 4 }}
  servers:
  - port:
      number: {{ .Values.postgresql.istio.gateway.port }}
      name: tcp-postgres
      protocol: tcp
    hosts:
    - {{ default .Values.global.sparHostname .Values.postgresql.istio.gateway.host | quote }}
    {{- if .Values.postgresql.istio.gateway.tls.enabled }}
    tls:
      {{- toYaml (omit .Values.postgresql.istio.gateway.tls "enabled") | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
