{{- if .Values.postgresql.enabled }}
{{- if .Values.postgresql.istio.enabled }}
{{- if .Values.postgresql.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  labels:
    {{- include "spar.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ default .Values.global.sparHostname .Values.postgresql.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (include "postgresql.v1.primary.fullname" .Subcharts.postgresql) .Values.postgresql.istio.virtualservice.gateway }}
  tcp:
  - match:
    - port: {{ .Values.postgresql.istio.virtualservice.matchPort }}
    route:
    - destination:
        host: {{ tpl .Values.postgresql.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.postgresql.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
{{- end }}
