hostname: spar.openg2p.sandbox.net

replicaCount: 1
image:
  repository: openg2p/openg2p-spar-mapper-api
  tag: "1.1"
  pullPolicy: Always

openapiRootPath: /api/mapper

envVars:
  SPAR_MAPPER_PORT: '{{ .Values.containerPort }}'
  SPAR_MAPPER_DB_HOSTNAME: '{{ tpl .Values.postgresqlInstallationName $ }}'
  SPAR_MAPPER_DB_USERNAME: "sparuser"
  SPAR_MAPPER_DB_DBNAME: "spardb"
  SPAR_MAPPER_OPENAPI_ROOT_PATH: '{{ tpl .Values.openapiRootPath $ }}'

envVarsFrom:
  SPAR_MAPPER_DB_PASSWORD:
    secretKeyRef:
      name: '{{ tpl .Values.postgresqlInstallationName $ }}'
      key: password

containerPort: 8000

service:
  type: ClusterIP
  port: 80

resources: {}
  #  requests:
  #    cpu: 500m
  #    memory: 2G

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

startupProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5

livenessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  helm.sh/revision: '{{ .Release.Revision }}'

podSecurityContext:
  enabled: false
  # fsGroup: 2000

containerSecurityContext:
  enabled: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}

updateStrategy:
  type: RollingUpdate

command: []
args: []

postgresCheckerInit:
  enabled: true
  image:
    repository: jbergknoff/postgresql-client
    tag: latest
    pullPolicy: IfNotPresent
  command:
  - 'sh'
  args:
  - '-c'
  - 'until pg_isready -U ${SPAR_MAPPER_DB_USERNAME} -h ${SPAR_MAPPER_DB_HOSTNAME} -p ${SPAR_MAPPER_DB_PORT:-5432} -d ${SPAR_MAPPER_DB_DBNAME:-spar_db}; do sleep 3; done'
  containerSecurityContext:
    enabled: false

ingress:
  enabled: false
  ingressClassName: ""
  pathType: ImplementationSpecific
  backendServiceName: '{{ include "common.names.fullname" . }}'
  path: '{{ tpl .Values.openapiRootPath $ }}(/|$)(.*)'
  apiVersion: ""
  hostname: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  tls: false
  tlsSecret: ""
  extraPaths: []
  extraTls: []
  extraRules: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ include "common.names.fullname" . }}'
    destinationPort: '{{ .Values.service.port }}'
    prefix: '{{ tpl .Values.openapiRootPath $ }}/'
    rewriteUri: "/"
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""

postgresqlInstallationName: '{{ .Release.Name }}-postgresql'
