{{- if or .Values.oauthPkce.enabled .Values.loginProviders }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.oauthPkce.enabled }}
  # Until this is enabled to be generated at runtime, this need to be passed as secret.
  oauth-pkce-code-verifier: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "oauth-pkce-code-verifier" "length" 32 "providedValues" (list "oauthPkce.codeVerifier") "context" $) }}
  {{- end }}
  {{- if .Values.loginProviders }}
  login-providers-list: >-
    {{- include "sparSelfservice.yamlListToJsonString" (dict "value" .Values.loginProviders "context" $) | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
