envVars:
  SPAR_MAPPER_DB_HOSTNAME: "postgres-postgresql.postgres"
  SPAR_MAPPER_DB_DBNAME: "spar_qa"
  SPAR_MAPPER_DB_USERNAME: "sparuser"

envVarsFrom:
  SPAR_MAPPER_DB_PASSWORD:
    secretKeyRef:
      name: "postgres-postgresql"
      key: password