apiVersion: v2
name: spar-self-service-api
description: A Helm chart for SPAR Self Service API Backend
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.x.x
  condition: redis.enabled

