hostname: spar.openg2p.sandbox.net

replicaCount: 1
image:
  repository: openg2p/openg2p-spar-self-service-ui
  tag: "1.1"
  pullPolicy: Always

envVars:
  NEXT_PUBLIC_BASE_PATH: /selfservice
  NEXT_PUBLIC_BASE_API_PATH: /api/selfservice

envVarsFrom: {}

containerPort: 3000

service:
  type: ClusterIP
  port: 80

resources: {}
  #  requests:
  #    cpu: 500m
  #    memory: 2G

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

startupProbe:
  enabled: true
  httpGet:
    path: /selfservice
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /selfservice
    port: http
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5

livenessProbe:
  enabled: true
  httpGet:
    path: /selfservice
    port: http
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5

podAnnotations:
  helm.sh/revision: '{{ .Release.Revision }}'

podSecurityContext:
  enabled: false
  # fsGroup: 2000

containerSecurityContext:
  enabled: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}

updateStrategy:
  type: RollingUpdate

command: []
args: []

ingress:
  enabled: false
  ingressClassName: ""
  pathType: ImplementationSpecific
  backendServiceName: '{{ include "common.names.fullname" . }}'
  path: /
  apiVersion: ""
  hostname: ""
  annotations: {}
  tls: false
  tlsSecret: ""
  extraPaths: []
  extraTls: []
  extraRules: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ include "common.names.fullname" . }}'
    destinationPort: '{{ .Values.service.port }}'
    prefix: /selfservice
    rewriteUri: ""
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""
