apiVersion: v2
name: spar-self-service-api
description: A Helm chart for OpenG2P SPAR Self Service API
type: application
version: 1.0.0
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
  condition: postgresql.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
