{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "selfserviceUi.fullname" . }}
  labels:
    {{- include "selfserviceUi.labels" . | nindent 4 }}
spec:
  hosts:
  {{- if .Values.istio.virtualservice.host }}
  - {{ .Values.istio.virtualservice.host }}
  {{- else }}
  - {{ .Values.global.hostname }}
  {{- end }}
  gateways:
    {{- if not .Values.istio.virtualservice.gateway }}
    - {{ include "openg2p.fullname" . }}
    {{- else }}
    - {{ .Values.istio.virtualservice.gateway }}
    {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.virtualservice.prefix }}
    {{- if .Values.istio.virtualservice.rewriteUri }}
    rewrite:
      uri: {{ .Values.istio.virtualservice.rewriteUri }}
    {{- end }}
    route:
    - destination:
        host: {{ include "selfserviceUi.fullname" . }}
        port:
          number: {{ .Values.service.port }}
  {{- with .Values.istio.virtualservice.api }}
  {{- if .enabled }}
  - match:
    - uri:
        prefix: {{ .prefix }}
    {{- if .rewriteUri }}
    rewrite:
      uri: {{ .rewriteUri }}
    {{- end }}
    route:
    - destination:
        host: {{ tpl .serviceName $ }}
        port:
          number: {{ .servicePort }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
